name: crud_table
description: CRUD Table Flutter is a package for crating CURD-UI for your entity/object/class easily. It consists of a Lazy loading function, resizable columns, and integrated CRUD Form.
version: 0.0.7
homepage: https://github.com/ireshmw/crud_table
repository: https://github.com/ireshmw/crud_table
issue_tracker: https://github.com/ireshmw/crud_table/issues

screenshots:
  - description: "CRUD Table Explain"
    path: img/crud_table_ui_explain.jpg
  - description: "CRUD Table Image 2"
    path: img/crud_table_img2.png
  - description: "CRUD Table Image"
    path: img/crud_table_img.png

topics:
  - crud-table
  - flutter-table
  - crud-ui
  - riverpod-crud
  - flutter-crud-table

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  fluid_kit: ^3.0.0
  flutter_riverpod: ^2.4.3
  split_view: ^3.2.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# The following section is specific to Flutter.
flutter:
